spring:
  appication:
    name: spring-jms-auditing
server:
  port: 8085
##  JPA / HIBERNATE
## Naming strategy
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
service_bus:
  consumerQueue: auditConsumerQueue
  deadLetterQueue: dditDeadLetterQueue

jms:
  username: admin
  password: admin
  remoteUri: amqp://victor:5672?maximumConnections=1000&wireFormat.maxFrameSize=1048
# Database
db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//localhost:1521/orcl
  username: system
  password: password

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.Oracle12cDialect
  show_sql: true
  hbm2ddl.auto: create-update

entitymanager.packagesToScan: com.vm.jms